server:
  prot: 8080
  ssl.key-store: classpath:1893737_vehicle.jshsoft.com.pfx
  ssl.key-store-password: MLY2ahO3
  ssl.keyStoreType: PKCS12
  ssl.protocols: TLSv1 TLSv1.1 TLSv1.2;

spring:
  servlet:
      multipart:
         enabled: true
         max-file-size: 20MB
         max-request-size: 200MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.105.85.203:3306/examine?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: qwe234*()
      initial-size: 5
      min-idle: 1
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
fileUpload:
  rootSavePath: /home/upload/sign/
  rootHttpPath: https://39.105.85.203/images/
file:
  staticAccessPath: /upload/*
  uploadFolder: /root/uploadImg
#mybatis:
#  type-aliases-package: com.lzdn.examine.entity
#  mapper-locations: classpath:mappers/*.xml
mybatis-plus:
  type-aliases-package: com.lzdn.examine.entity
  mapper-locations: classpath:mappers/*.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    b-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
